Login Fix
- fixing the kore login command when the configuration is empty

[jest@starfury kore]$ kore login -a http://localhost:10080 local
Unable to authenticate: no profile selected
You may need to reconfigure your profile via $ kore profile configure
Error: invalid profile

Afterward

[jest@starfury kore]$ kore login -a http://localhost:10080 local
Attempting to authenticate to Kore: http://localhost:10080 [local]
Successfully authenticated to local